// Package svg exports a go-cad document as a standards-compliant SVG file.
//
// Each layer maps to an SVG <g> element with id="layer-N" and
// data-name="LayerName". Line types are mapped to stroke-dasharray patterns.
// Text entities are rendered as <text> elements.
package svg

import (
	"fmt"
	"io"
	"math"
	"strings"

	"github.com/tomott12345/go-cad/internal/document"
)

const margin = 10.0 // units around the drawing

// Write exports doc as an SVG document to w.
// The viewBox is computed from the bounding box of all entities.
func Write(doc *document.Document, w io.Writer) error {
	s, err := Generate(doc)
	if err != nil {
		return err
	}
	_, err = io.WriteString(w, s)
	return err
}

// Generate returns the SVG document as a string.
func Generate(doc *document.Document) (string, error) {
	entities := doc.Entities()
	layers := doc.Layers()

	// ── Compute bounding box ─────────────────────────────────────────────────
	minX, minY, maxX, maxY := math.MaxFloat64, math.MaxFloat64, -math.MaxFloat64, -math.MaxFloat64
	updateBB := func(x, y float64) {
		if x < minX {
			minX = x
		}
		if y < minY {
			minY = y
		}
		if x > maxX {
			maxX = x
		}
		if y > maxY {
			maxY = y
		}
	}
	for _, e := range entities {
		switch e.Type {
		case document.TypeLine, document.TypeRectangle:
			updateBB(e.X1, e.Y1)
			updateBB(e.X2, e.Y2)
		case document.TypeCircle:
			updateBB(e.CX-e.R, e.CY-e.R)
			updateBB(e.CX+e.R, e.CY+e.R)
		case document.TypeArc, document.TypeEllipse:
			updateBB(e.CX-e.R, e.CY-e.R)
			updateBB(e.CX+e.R, e.CY+e.R)
		case document.TypePolyline, document.TypeSpline, document.TypeNURBS:
			for _, pt := range e.Points {
				if len(pt) >= 2 {
					updateBB(pt[0], pt[1])
				}
			}
		case document.TypeText, document.TypeMText:
			updateBB(e.X1, e.Y1)
		}
	}
	if minX == math.MaxFloat64 {
		minX, minY, maxX, maxY = 0, 0, 210, 297 // default A4 if no entities
	}
	vbX := minX - margin
	vbY := minY - margin
	vbW := (maxX - minX) + 2*margin
	vbH := (maxY - minY) + 2*margin

	// ── Build layer map (ID → layer) ──────────────────────────────────────────
	layerMap := make(map[int]*document.Layer, len(layers))
	for _, l := range layers {
		lCopy := l
		layerMap[l.ID] = lCopy
	}

	// ── Group entities by layer ────────────────────────────────────────────────
	type group struct {
		layer   *document.Layer
		entities []document.Entity
	}
	layerOrder := make([]int, 0, len(layers))
	layerGroups := make(map[int]*group)
	for _, l := range layers {
		layerOrder = append(layerOrder, l.ID)
		lCopy := l
		layerGroups[l.ID] = &group{layer: lCopy}
	}
	for _, e := range entities {
		if _, ok := layerGroups[e.Layer]; !ok {
			layerGroups[e.Layer] = &group{layer: &document.Layer{ID: e.Layer, Color: "#ffffff", Visible: true}}
			layerOrder = append(layerOrder, e.Layer)
		}
		layerGroups[e.Layer].entities = append(layerGroups[e.Layer].entities, e)
	}

	// ── Render ────────────────────────────────────────────────────────────────
	var sb strings.Builder
	fmt.Fprintf(&sb,
		`<?xml version="1.0" encoding="UTF-8"?>`+"\n"+
			`<svg xmlns="http://www.w3.org/2000/svg"`+
			` viewBox="%.4f %.4f %.4f %.4f"`+
			` width="%.4fmm" height="%.4fmm">`+"\n",
		vbX, vbY, vbW, vbH, vbW, vbH)

	sb.WriteString("  <desc>Generated by go-cad</desc>\n")

	for _, layID := range layerOrder {
		grp := layerGroups[layID]
		if grp == nil || len(grp.entities) == 0 {
			continue
		}
		l := grp.layer
		if !l.Visible {
			continue
		}
		color := l.Color
		dashArray := ltypeToDashArray(l.LineTyp)
		lw := l.LineWeight
		if lw <= 0 {
			lw = 0.25
		}
		layName := l.Name
		if layName == "" {
			layName = fmt.Sprintf("layer-%d", layID)
		}
		fmt.Fprintf(&sb, `  <g id="layer-%d" class="layer" data-name="%s"`, layID, xmlEsc(layName))
		fmt.Fprintf(&sb, ` fill="none" stroke="%s" stroke-width="%.4f"`, color, lw)
		if dashArray != "" {
			fmt.Fprintf(&sb, ` stroke-dasharray="%s"`, dashArray)
		}
		sb.WriteString(">\n")

		for _, e := range grp.entities {
			entityColor := e.Color
			if strings.EqualFold(entityColor, "BYLAYER") || entityColor == "" {
				entityColor = ""
			}
			svgEntity(&sb, e, entityColor)
		}
		sb.WriteString("  </g>\n")
	}
	sb.WriteString("</svg>\n")
	return sb.String(), nil
}

// svgEntity renders a single entity to the SVG builder.
func svgEntity(sb *strings.Builder, e document.Entity, colorOverride string) {
	strokeAttr := ""
	if colorOverride != "" {
		strokeAttr = fmt.Sprintf(` stroke="%s"`, colorOverride)
	}
	switch e.Type {
	case document.TypeLine:
		fmt.Fprintf(sb, `    <line x1="%.4f" y1="%.4f" x2="%.4f" y2="%.4f"%s/>`+"\n",
			e.X1, e.Y1, e.X2, e.Y2, strokeAttr)

	case document.TypeCircle:
		fmt.Fprintf(sb, `    <circle cx="%.4f" cy="%.4f" r="%.4f"%s/>`+"\n",
			e.CX, e.CY, e.R, strokeAttr)

	case document.TypeArc:
		// Convert arc to SVG path arc command.
		d := arcToPath(e.CX, e.CY, e.R, e.StartDeg, e.EndDeg)
		fmt.Fprintf(sb, `    <path d="%s"%s/>`+"\n", d, strokeAttr)

	case document.TypeRectangle:
		x := math.Min(e.X1, e.X2)
		y := math.Min(e.Y1, e.Y2)
		w := math.Abs(e.X2 - e.X1)
		h := math.Abs(e.Y2 - e.Y1)
		fmt.Fprintf(sb, `    <rect x="%.4f" y="%.4f" width="%.4f" height="%.4f"%s/>`+"\n",
			x, y, w, h, strokeAttr)

	case document.TypePolyline:
		if len(e.Points) < 2 {
			return
		}
		sb.WriteString(`    <polyline points="`)
		for i, pt := range e.Points {
			if i > 0 {
				sb.WriteString(" ")
			}
			if len(pt) >= 2 {
				fmt.Fprintf(sb, "%.4f,%.4f", pt[0], pt[1])
			}
		}
		fmt.Fprintf(sb, `"%s/>`+"\n", strokeAttr)

	case document.TypeSpline, document.TypeNURBS:
		// Approximate as polyline
		pts := approxCurve(e, 40)
		if len(pts) < 2 {
			return
		}
		sb.WriteString(`    <polyline points="`)
		for i, pt := range pts {
			if i > 0 {
				sb.WriteString(" ")
			}
			fmt.Fprintf(sb, "%.4f,%.4f", pt[0], pt[1])
		}
		fmt.Fprintf(sb, `"%s/>`+"\n", strokeAttr)

	case document.TypeEllipse:
		rot := e.RotDeg
		fillAttr := ` fill="none"`
		if colorOverride != "" {
			fmt.Fprintf(sb, `    <ellipse cx="%.4f" cy="%.4f" rx="%.4f" ry="%.4f" transform="rotate(%.4f,%.4f,%.4f)"%s%s/>`+"\n",
				e.CX, e.CY, e.R, e.R2, rot, e.CX, e.CY, fillAttr, strokeAttr)
		} else {
			fmt.Fprintf(sb, `    <ellipse cx="%.4f" cy="%.4f" rx="%.4f" ry="%.4f" transform="rotate(%.4f,%.4f,%.4f)"%s/>`+"\n",
				e.CX, e.CY, e.R, e.R2, rot, e.CX, e.CY, fillAttr)
		}

	case document.TypeText:
		h := e.TextHeight
		if h <= 0 {
			h = 2.5
		}
		fillColor := e.Color
		if strings.EqualFold(fillColor, "BYLAYER") || fillColor == "" {
			fillColor = "inherit"
		}
		fmt.Fprintf(sb,
			`    <text x="%.4f" y="%.4f" font-size="%.4f" fill="%s" transform="rotate(%.4f,%.4f,%.4f)">%s</text>`+"\n",
			e.X1, e.Y1, h, fillColor, -e.RotDeg, e.X1, e.Y1, xmlEsc(e.Text))

	case document.TypeMText:
		h := e.TextHeight
		if h <= 0 {
			h = 2.5
		}
		fillColor := e.Color
		if strings.EqualFold(fillColor, "BYLAYER") || fillColor == "" {
			fillColor = "inherit"
		}
		lines := strings.Split(e.Text, "\n")
		for i, line := range lines {
			fmt.Fprintf(sb,
				`    <text x="%.4f" y="%.4f" font-size="%.4f" fill="%s">%s</text>`+"\n",
				e.X1, e.Y1+float64(i)*h*1.5, h, fillColor, xmlEsc(line))
		}
	}
}

// arcToPath converts an arc entity to an SVG path "d" attribute string.
func arcToPath(cx, cy, r, startDeg, endDeg float64) string {
	span := endDeg - startDeg
	for span <= 0 {
		span += 360
	}
	if span >= 360 {
		// Full circle: use two half-arcs.
		mid := startDeg + 180
		mx := cx + r*math.Cos(mid*math.Pi/180)
		my := cy + r*math.Sin(mid*math.Pi/180)
		sx := cx + r*math.Cos(startDeg*math.Pi/180)
		sy := cy + r*math.Sin(startDeg*math.Pi/180)
		return fmt.Sprintf("M %.4f %.4f A %.4f %.4f 0 0 1 %.4f %.4f A %.4f %.4f 0 0 1 %.4f %.4f Z",
			sx, sy, r, r, mx, my, r, r, sx, sy)
	}
	x1 := cx + r*math.Cos(startDeg*math.Pi/180)
	y1 := cy + r*math.Sin(startDeg*math.Pi/180)
	x2 := cx + r*math.Cos(endDeg*math.Pi/180)
	y2 := cy + r*math.Sin(endDeg*math.Pi/180)
	largeArc := 0
	if span > 180 {
		largeArc = 1
	}
	return fmt.Sprintf("M %.4f %.4f A %.4f %.4f 0 %d 1 %.4f %.4f",
		x1, y1, r, r, largeArc, x2, y2)
}

// approxCurve returns sample points for spline/NURBS entities.
func approxCurve(e document.Entity, n int) [][2]float64 {
	pts := make([][2]float64, len(e.Points))
	for i, p := range e.Points {
		if len(p) >= 2 {
			pts[i] = [2]float64{p[0], p[1]}
		}
	}
	return pts
}

// ltypeToDashArray maps a document LineType to an SVG stroke-dasharray value.
func ltypeToDashArray(lt document.LineType) string {
	switch lt {
	case document.LineTypeDashed:
		return "12,6"
	case document.LineTypeDotted:
		return "2,4"
	case document.LineTypeDashDot:
		return "12,4,2,4"
	case document.LineTypeCenter:
		return "24,4,4,4"
	case document.LineTypeHidden:
		return "8,4"
	default:
		return ""
	}
}

// xmlEsc escapes XML special characters.
func xmlEsc(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, `"`, "&quot;")
	return s
}
